# use with podman play cube
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ibutsu
  name: ibutsu
spec:
  containers:
  - name: postgres
    image: docker.io/library/postgres:latest
    resources: &resources-small
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    volumeMounts:
    - name: ibutsu-database
      mountPath: /var/lib/postgresql/data
    env: &all-env
      - name: POSTGRES_DB
        value: ibutsu
      - name: POSTGRES_USER
        value: ibutsu
      - name: POSTGRES_PASSWORD
        value: ibutsu
      - name: POSTGRES_HOSTNAME
        value: ibutsu
      # for the backend conainers
      - name: CELERY_BROKER_URL
        value: redis://ibutsu
      - name: CELERY_RESULT_BACKEND
        value: redis://ibutsu
      - name: IBUTSU_SUPERADMIN_EMAIL
        value: ibutsu@ronnypfannschmidt.de
      - name: IBUTSU_SUPERADMIN_PASSWORD
        value: abc123
      - name: IBUTSU_SUPERADMIN_OWN_PROJECT
        value: test
      - name: JWT_SECRET
        value: xkcd-random-4

  - name: redis
    image: docker.io/library/redis:latest
    resources: *resources-small
  - name: backend
    image: backend
    args: [ devserver]
    env: *all-env
    resources: *resources-small
    securityContext: &security-context
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    volumeMounts:
    - mountPath: /srv/:Z
      name: ibutsu-server-backend
    ports:
     - containerPort: 8080
       hostPort: 8080
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
  - name: worker
    image: backend
    args:
    - worker
    env: *all-env
    resources: *resources-small
    securityContext: *security-context
    volumeMounts:
    - mountPath: /srv/:Z
      name: ibutsu-server-backend
  - name: frontend
    image: docker.io/library/node:latest
    args:
    - /bin/bash
    - -c
    - |-
      yarn install && CI=TRUE yarn run devserver
    env:
    - name: NODE_OPTIONS
      value: --openssl-legacy-provider
    - name: CI
      value: "true"
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "768Mi"
        cpu: "500m"
      ulimit: 20000
    securityContext:
      privileged: false
      readOnlyRootFilesystem: false
    volumeMounts:
    - mountPath: /src/:Z
      name: ibutsu-server-frontend
    ports:
     - containerPort: 3000
       hostPort: 3000
    workingDir: /src/

  volumes:
  - hostPath:
      path: ./backend
      type: Directory
    name: ibutsu-server-backend
  - hostPath:
      path: ./frontend
      type: Directory
    name: ibutsu-server-frontend
  - name: ibutsu-database
    persistentVolumeClaim:
      claimName: ibutsu-database
