apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: insights-qe-tenant-namespace
  annotations:
    description: "Insights QE TenantNamespace template"
objects:
  - apiVersion: tenant.paas.redhat.com/v1alpha1
    kind: TenantNamespace
    metadata:
      name: "${NAMESPACE_NAME}"
      namespace: "${TENANT_NAME}--config"
    spec:
      type: "${NAMESPACE_TYPE}"
      network:
        security-zone: "${NETWORK_SECURITY_ZONE}"

parameters:
  - description: Tenant Name
    name: TENANT_NAME
    value: insights-qe-gpc
    required: true
  - description: Namespace name
    name: NAMESPACE_NAME
    required: true
    value: ibutsu
  - description: Namespace type, can be build or runtime
    name: NAMESPACE_TYPE
    required: true
    value: runtime
  - description: Network security zone
    name: NETWORK_SECURITY_ZONE
    value: internal
    required: true

labels:
  template: insights-qe-tenant-namespace
